// Regenerates src/lib/psl-data.ts from the official Public Suffix List.
// Run: npm run update-psl — then commit the result.
//
// Only the ICANN section is kept: the private section (github.io, s3
// buckets, …) describes delegation policy of private operators, not registry
// boundaries — including it would make e.g. "user.github.io" look like a
// registered domain, which is wrong for RDAP lookups. Rules are converted to
// punycode at generation time so runtime matching is a plain ASCII Set lookup.

import { writeFileSync } from "node:fs";
import { domainToASCII } from "node:url";

const SOURCE = "https://publicsuffix.org/list/public_suffix_list.dat";

const res = await fetch(SOURCE);
if (!res.ok) {
  throw new Error(`fetch failed: HTTP ${res.status} from ${SOURCE}`);
}
const text = await res.text();

const begin = text.indexOf("// ===BEGIN ICANN DOMAINS===");
const end = text.indexOf("// ===END ICANN DOMAINS===");
if (begin === -1 || end === -1 || end < begin) {
  throw new Error("ICANN section markers not found — PSL format changed?");
}

const exact = [];
const wildcard = [];
const exceptions = [];

for (let line of text.slice(begin, end).split("\n")) {
  line = line.trim();
  if (line === "" || line.startsWith("//")) continue;
  let bucket = exact;
  if (line.startsWith("!")) {
    bucket = exceptions;
    line = line.slice(1);
  } else if (line.startsWith("*.")) {
    bucket = wildcard;
    line = line.slice(2);
  }
  const ascii = domainToASCII(line);
  if (ascii === "") {
    throw new Error(`could not punycode PSL rule: ${line}`);
  }
  bucket.push(ascii);
}

for (const list of [exact, wildcard, exceptions]) list.sort();

if (exact.length < 5000) {
  throw new Error(`suspiciously few ICANN rules (${exact.length}) — refusing to write`);
}

const stamp = new Date().toISOString().slice(0, 10);
const out = `// Generated by scripts/update-psl.mjs on ${stamp} — do not edit.
// Source: ${SOURCE} (ICANN section only, rules punycoded).
// ${exact.length} exact, ${wildcard.length} wildcard, ${exceptions.length} exception rules.

export const PSL_EXACT: string[] = ${JSON.stringify(exact)};

export const PSL_WILDCARD: string[] = ${JSON.stringify(wildcard)};

export const PSL_EXCEPTIONS: string[] = ${JSON.stringify(exceptions)};

export const PSL_GENERATED = "${stamp}";
`;

writeFileSync("src/lib/psl-data.ts", out);
console.log(
  `psl-data.ts written: ${exact.length} exact, ${wildcard.length} wildcard, ${exceptions.length} exception rules`,
);
